name: Android CI(Debug)

on:
  release:
    types: [published]
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build with gradle
        run: |
          echo "开始进行Debug构建"
          chmod +x gradlew
          ./gradlew app:assembleDebug
      - name: Release apk
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: "app/build/outputs/apk/debug/*.apk"
          token: ${{ secrets.RELEASE_TOKEN }}
          prerelease: true
